######################################################################
# Automatically generated by qmake (2.01a) mer. déc. 23 14:10:28 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += pong.hpp
SOURCES += main.cpp pong.cpp
