######################################################################
# Automatically generated by qmake (2.01a) Sun Jan 17 23:54:46 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += pong.hpp
SOURCES += main.cpp pong.cpp
