######################################################################
# Automatically generated by qmake (2.01a) jeu. nov. 19 14:55:55 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ball.hpp gameboard.hpp
SOURCES += ball.cpp gameboard.cpp main.cpp
