######################################################################
# Automatically generated by qmake (2.01a) lun. nov. 23 00:16:45 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ball.hpp gameboard.hpp
SOURCES += ball.cpp gameboard.cpp main.cpp
