######################################################################
# Automatically generated by qmake (2.01a) sam. nov. 21 15:38:07 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ball.hpp gameboard.hpp
SOURCES += ball.cpp gameboard.cpp main.cpp
