######################################################################
# Automatically generated by qmake (2.01a) jeu. déc. 17 00:38:23 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . users
INCLUDEPATH += .

# Input
HEADERS += gamesession.hpp \
           startwindow.hpp \
           user.hpp \
           userwindow.hpp \
           users/gamesession.hpp
SOURCES += gamesession.cpp main.cpp startwindow.cpp user.cpp userwindow.cpp
