######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 22 22:03:44 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gamesession.hpp \
           gamewindow.hpp \
           pong.hpp \
           startwindow.hpp \
           user.hpp \
           userwindow.hpp
SOURCES += gamesession.cpp \
           gamewindow.cpp \
           main.cpp \
           pong.cpp \
           startwindow.cpp \
           user.cpp \
           userwindow.cpp
