######################################################################
# Automatically generated by qmake (2.01a) jeu. déc. 17 12:00:52 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gamesession.hpp startwindow.hpp user.hpp userwindow.hpp
SOURCES += gamesession.cpp main.cpp startwindow.cpp user.cpp userwindow.cpp
