######################################################################
# Automatically generated by qmake (2.01a) lun. nov. 23 01:55:19 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ball.hpp gameboard.hpp player.hpp
SOURCES += ball.cpp gameboard.cpp main.cpp player.cpp
