######################################################################
# Automatically generated by qmake (2.01a) dim. nov. 22 17:05:02 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ball.hpp gameboard.hpp
SOURCES += ball.cpp gameboard.cpp main.cpp
