######################################################################
# Automatically generated by qmake (2.01a) mar. nov. 24 17:56:56 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gamesession.hpp gamewindow.hpp
SOURCES += gamesession.cpp gamewindow.cpp main.cpp
