######################################################################
# Automatically generated by qmake (2.01a) lun. nov. 16 16:14:54 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gameboard.h gameboard.hpp
SOURCES += gameboard.cpp main.cpp
