######################################################################
# Automatically generated by qmake (2.01a) mer. janv. 20 23:13:11 2010
######################################################################

TEMPLATE = lib
CONFIG += plugin
TARGET = sg_pong
DEPENDPATH += .
INCLUDEPATH += ../
DESTDIT += ../

# Input
HEADERS += pong.hpp
SOURCES += pong.cpp
