######################################################################
# Automatically generated by qmake (2.01a) mer. janv. 20 23:20:25 2010
######################################################################

TEMPLATE = lib
CONFIG += plugin 
TARGET = 
DEPENDPATH += .
INCLUDEPATH += ../
DESTDIR += .

# Input
HEADERS += testplugin.hpp
SOURCES += testplugin.cpp
