######################################################################
# Automatically generated by qmake (2.01a) mar. déc. 15 09:35:05 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gamesession.hpp profilewindow.hpp startwindow.hpp userwindow.hpp
SOURCES += gamesession.cpp \
           main.cpp \
           profilewindow.cpp \
           startwindow.cpp \
           userwindow.cpp
