######################################################################
# Automatically generated by qmake (2.01a) sam. déc. 12 20:12:43 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gamesession.hpp startwindow.hpp
SOURCES += gamesession.cpp main.cpp startwindow.cpp
