######################################################################
# Automatically generated by qmake (2.01a) mer. déc. 16 23:21:09 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gamesession.hpp \
           profilewindow.hpp \
           startwindow.hpp \
           user.hpp \
           userwindow.hpp
SOURCES += gamesession.cpp \
           main.cpp \
           profilewindow.cpp \
           startwindow.cpp \
           user.cpp \
           userwindow.cpp
